### ISSUE TITLE
Don't forefront nudge when macOS installer is in forefront

### ISSUE THREAD

**Issue by MScottBlake** [erikng/nudge#12]
Nudge shouldn't be brought to the forefront when the macOS installer is in the forefront. This is especially problematic when the cutoff data has passed and it is being elevated every 10 seconds without an option to close nudge.

**Comment by LcTrKiD** [comment]
This was addresed here: https://github.com/macadmins/nudge/blob/master/payload/Library/nudge/Resources/nudge#L44-L79
