### ISSUE TITLE
Nudge should be able to parse softwareupdate and open based on that rather than a hard coded OS version

### ISSUE THREAD

**Issue by grahamgilbert** [erikng/nudge#3]
At present we need to update the LaunchAgent every time we want to enforce an update. Nudge should be able to use softwareupdate, and activate if there are updates that require a restart. 

Optionally we could also auto install updates if the app is not open, and pop nudge open if they are open (to fully replicate the present unattended apple updates behavior in Munki).

**Comment by gregneagle** [comment]
I don't think nudge should itself attempt to install anything.

**Comment by grahamgilbert** [comment]
Okay, so perhaps open on all updates if automatic updates aren't configured, and if they are open only on updates that require a restart.

**Comment by erikng** [comment]
I like this idea about popping up based on softwareupdate status.

Should it dynamically open the App Store updates tab vs the app? `macappstore://showUpdatesPage`

**Comment by gregneagle** [comment]
App Store updates? I though this was about Apple software updates

**Comment by grahamgilbert** [comment]
It should open right to the updates page as the goal is to get users to install Apple updates, not whatever is featured in the App Store this week.

**Comment by gregneagle** [comment]
And of course should not open the App Store at all on Mojave+

**Comment by gregneagle** [comment]
I see the potential for terrible UX under macOS < Mojave -- 

App Store is opened to the Updates page, which lists Apple updates and also some App Store apps that perhaps they don't actually have the credentials/AppleID to update...

That could definitely happen here.

**Comment by erikng** [comment]
Oh right that's what I meant. 

And yeah that definitely could happen. We could potentially do something really hacky, but would require root access.

Deploy a temporary profile to disable the App Store and limit it to updates only. A terribly hacky idea, but an idea nonetheless.
