### ISSUE TITLE
last_seen should update when the notification window appears

### ISSUE THREAD

**Issue by aysiu** [erikng/nudge#34]
Right now, there are several places the `last_seen` pref gets updated:

- [If there are no pending Apple updates, `last_seen` gets set to none.](https://github.com/erikng/nudge/blob/master/payload/Library/nudge/Resources/nudge#L481-L485)
- [If there are Apple updates that can be installed in the background, `last_seen` also gets set to none.](https://github.com/erikng/nudge/blob/master/payload/Library/nudge/Resources/nudge#L507-L511)
- [If `last_seen` has not been set at all, it gets set.](https://github.com/erikng/nudge/blob/master/payload/Library/nudge/Resources/nudge#L534-L537)

But it doesn't actually get set any other time, and it probably should be set [when the notification window appears.](https://github.com/erikng/nudge/blob/master/payload/Library/nudge/Resources/nudge#L693-L695)

**Comment by erikng** [comment]
Merged
