### ISSUE TITLE
Read enforcement dates from a configuration file

### ISSUE THREAD

**Issue by grahamgilbert** [erikng/nudge#4]
Rather than having global enforcement dates, if Munki is installed and configured, it would be useful if nudge can use Munki's catalogs for force install times for Apple Updates.

**Comment by gregneagle** [comment]
I'm not convinced tightly tying this tool to Munki is a good idea. Nudge needs a config file containing updates it's interested in and due dates.  That config file could then by generated by Puppet or Chef or  Jamf Pro or some tool that integrates with Munki.

**Comment by erikng** [comment]
I agree with @gregneagle here though I am intrigued by the idea.

Right now nudge (and UMAD) are limited by python options passed through the launchagent, requiring an admin to deploy a new package of the application or controlling it with some kind of CM tool.

A config file (preferably a mobileconfig) would be a much more flexible option. If an admin needed more granularity, multiple mobileconfigs could be pushed that minimic the pkginfo files of apple updates. Munki or a CM tool could handle this logic and probably better suited.

That said I'm not fully opposed to this idea and if it wasn't too much work I would merge it in.

Another option would be this concept I've been thinking about for my tools, like munki middleware, which would allow a company to change the behavior of my tools without maintaining a separate fork.

**Comment by grahamgilbert** [comment]
Okay, I updated the title of the issue to reflect what I meant more - updating the launchagent feels a bit manual to me. A config file (possibly a profile, so it can be deployed in multiple ways) that is outside of updating and reloading the launchagent is the point I was getting at.
