### ISSUE TITLE
Endless loop when json cannot be downloaded

### ISSUE THREAD

**Issue by bochoven** [erikng/nudge#45]
Although this is an edge case, I noticed nudge will loop forever (and write a huge log file) if it cannot download its json file.

The issue is caused by https://github.com/macadmins/nudge/blob/master/payload/Library/nudge/Resources/nudge#L432-L436

**Comment by erikng** [comment]
Nice find. I don't think I would extend the retry to the admin as an option, so what do you think is a reasonable retry if it's happening every half second? Maybe 60 retries (30 seconds)?
