### ISSUE TITLE
Update Machine button does not dismiss Nudge window

### ISSUE THREAD

**Issue by xirianlight** [erikng/nudge#47]
When clicking the "update machine" button, the Nudge window is not dismissed. Would it be possible to have the window dismiss (same behavior as clicking the "Close" button? It'd be nice to have the user sort of see that Nudge did its thing and ferried them to the next window (System Preferences or the OS installer) when they did what was asked of them (click the Update button). Could even be a .json argument to make that dismissal optional. Thanks!

**Comment by erikng** [comment]
It would definitely need to be an option and not default behavior because the user clicking the button doesn't mean they are actually going to perform the action.

This is key to the "aggressive UX" working as well so it would take some thought to implement this.
