### ISSUE TITLE
Nudge should be a proper app and proper app bundle

### ISSUE THREAD

**Issue by gregneagle** [erikng/nudge#5]
What I said in the title

**Comment by erikng** [comment]
Agreed. The reliance on nibbler means that I can't run this on 10.9.5, though it's only a temporary issue.

**Comment by grahamgilbert** [comment]
![tumblr_lsus5pi2iu1qht00ko6_500](https://user-images.githubusercontent.com/1208495/47941978-88c32900-dead-11e8-936b-49c51f9a26f3.gif)

**Comment by erikng** [comment]
https://github.com/macadmins/nudge is now up with a Swift version
