### ISSUE TITLE
build_python_framework uses python 3.8 which does not work with Big Sur

### ISSUE THREAD

**Issue by GuillaumeRoss** [erikng/nudge#51]
When following instructions from https://github.com/macadmins/nudge/blob/master/README.md - if you run build_python_framework - it does so using 3.8.

By packaging up the results of that and installing it on Big Sur, you get the following error in nudge logs:

`[Nudge] Detected Big Sur running version 10.16. Nudge cannot be reliably enforced. To fix this, create a Python.framework file on a machine running Big Sur or higher.
`

Then if I install https://github.com/macadmins/python and do `managed_python3 /Library/nudge/Resources/nudge` this error does not occur. 

So either the python build script should get a newer version, or documented should be updated to deprecate it and point to macadmins/python IMO.

Thanks!

**Comment by erikng** [comment]
I will be addressing this in a README change momentarily
