### ISSUE TITLE
understand issue as a basic learners

### ISSUE THREAD

**Issue by mani2care** [erikng/nudge#53]
Hi Nice to have seen the projects and more hard work 

as a beginner unable to understand the process.

Kindly have any video about the project explained step by step and easier to learn and also use for us.

where to start and how to start what needs to be installed where the files to be transferred or how to build the pkg.

is nay thing wrong pls ignore

**Comment by erikng** [comment]
There are no videos to explain this and this project is a bit under-documented. Given that this project is end-of-life, I won't be putting any more effort into this repo.

I would urge you to look at https://github.com/macadmins/nudge which is the new repo that contains much better documentation.
